#!/sbin/runscript

depend() {
	need net
}

start() {
	ebegin "Starting Wowza Media Server"

	if [ -z $(java-config-2 -f | grep 'sun-j.*-1\.6') ] ; then
		eerror "Java 1.6 required. Use java-config-2 to select Java 1.6 as a system VM."
		return 1
	fi

	if [ -z $(grep -E '([0-9A-Z]{5}(-|$)){5}' /etc/wowza-media-server/conf/Server.license) ] ; then
		eerror "The /etc/wowza-media-server/conf/Server.license file doesn't contain valid serial number!"
		return 1
	fi

	# Apply any ulimits if defined
	[[ -n ${RC_ULIMIT} ]] && ulimit -n ${RC_ULIMIT}

	# Get classpath of all modules
	MODULES_CP="$(java-config --classpath ${MODULES})"
	if [[ -z ${MODULES_CP} && -n ${MODULES} ]] ; then
		eerror "Please check your Wowza module list."
		return 1
	fi
	if [ -n ${MODULES_CP} ] ; then
		MODULES_CP=":${MODULES_CP}"
	fi

	JAVA_OPTS=${JAVA_OPTS} JMXOPTIONS=${JMXOPTIONS} CLASSPATH="${CLASSPATH}${MODULES_CP}" /usr/sbin/wowza-media-server start 2>&1 1>/var/log/wowza-media-server/wowzamediaserver_stdout.log &

	eend $? "Failed to start Wowza Media Server."
}

stop() {
	ebegin "Stopping Wowza Media Server"
	/usr/sbin/wowza-media-server stop
	eend $? "Failed to stop Wowza Media Server."
}
